name: Deploy Backend → Cloud Run

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # --- 1. DESPLIEGUE DE LA API WEB ---
      - name: Deploy API to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cfdi-suite-api
          region: us-central1
          source: ./backend
          env_vars: |
            ALLOWED_ORIGINS=${{ secrets.VERCEL_URL }}
            REDIS_HOST=dashing-aphid-43185.upstash.io
            REDIS_PORT=6379
            REDIS_PASSWORD=AaixAAIgcDFiMWQxODcwMzU4ZTY0NzgxOWM3Y2Y5ODllYWIyYTgwOA
            MODE=api
            API_URL=https://cfdi-suite-api-hfg67q6kbq-uc.a.run.app
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID }}
            PUSHER_KEY=${{ secrets.PUSHER_KEY }}
            PUSHER_SECRET=${{ secrets.PUSHER_SECRET }}
            PUSHER_CLUSTER=us2
          flags: |
            --allow-unauthenticated
            --cpu=2
            --memory=2Gi
            --max-instances=10
            --timeout=1800
            --concurrency=5
